# Generated by Django 5.0.2 on 2024-02-27 17:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0002_alter_trip_trip_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^TK\\d{8}$')])),
                ('traveller_name', models.CharField(max_length=100)),
                ('traveller_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('ticket_cost', models.FloatField()),
                ('traveller_email', models.EmailField(max_length=254)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip')),
            ],
        ),
    ]
