# Generated by Django 5.0.2 on 2024-02-27 18:16

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_id',
            field=models.CharField(default=booking.models.generate_ticket_id, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
