# Generated by Django 5.0.2 on 2024-02-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('route_name', models.CharField(max_length=100)),
                ('route_origin', models.CharField(max_length=100)),
                ('route_destination', models.CharField(max_length=100)),
                ('route_stops', models.JSONField()),
            ],
        ),
    ]
