# Generated by Django 5.0.2 on 2024-02-26 19:31

import route.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.CharField(default=route.models.generate_route_id, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
